sudo: required
services:
  - docker

before_install:
  - docker build -t ajduet/client -f Dockerfile.dev .

script:
  - docker run -e CI=true ajduet/client npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'react-docker-client'
  env: 'ReactDockerClient-env'
  bucket_name: 'elasticbeanstalk-us-west-1-367484709954'
  bucket_path: 'react-docker-client'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
